version: '3'

services:
  nginx:
    image: nginx:1.13.3-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    env_file: .env
    volumes:
      - data-wp:/var/www/html
      - data-db:/var/lib/mysql
      - ./setting/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./setting/nginx/conf:/etc/nginx/conf/:ro
      - ./setting/nginx/htpasswd:/etc/nginx/htpasswd/:ro
    networks:
      - front
      - back

  wordpress:
    build: ./docker/wordpress
    ports:
      - 9000
    env_file: .env
    volumes:
      - data-wp:/var/www/html
      - ./setting/wordpress:/usr/local/etc/php:ro
      - ./theme:/var/www/html/wp-content/themes/a:ro
    networks:
      - back

  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - back

  data:
    image: busybox:1.27.1-musl
    tty: true
    volumes:
      - data-wp:/var/www/html
      - data-db:/var/lib/mysql
      - ./backup:/backup
    networks:
      - back

  wpcli:
    image: tatemz/wp-cli
    tty: true
    volumes:
      - data-wp:/var/www/html
      - data-db:/var/lib/mysql
      - ./backup:/backup
    entrypoint: wp
    command: '--info'
    networks:
      - back

volumes:
  data-wp:
    external:
      name: ${WP_VOLUME_NAME}
  data-db:
    external:
      name: ${DB_VOLUME_NAME}

networks:
  front:
    external: true
  back:
