version: '3'

services:
  nginx:
    image: nginx:1.13.3-alpine
    ports:
      - 8080:80
    env_file: .env
    volumes:
      - data-wp:/var/www/html
      - data-db:/var/lib/mysql
      - ./setting/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./setting/nginx/conf:/etc/nginx/conf/:ro
      - ./setting/nginx/htpasswd:/etc/nginx/htpasswd/:ro
    networks:
      - front
      - back

  wordpress:
    build: ./docker/wordpress
    ports:
      - 9000
    env_file: .env
    volumes:
      - data-wp:/var/www/html
      - ./setting/wordpress:/usr/local/etc/php:ro
    networks:
      - back

  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - back

volumes:
  data-wp:
  data-db:

networks:
  front:
    external: true
  back:
